### ISSUE TITLE
Three similar repos

### ISSUE THREAD

**Issue by GabrielLin** [RichardeJiang/racode#1]
Could you please tell me what are the different between these three repos? Thanks.

https://github.com/RichardeJiang/racode
https://github.com/WING-NUS/ResearchTrends
https://github.com/RichardeJiang/ResearchTrends

**Comment by RichardeJiang** [comment]
Sorry for the confusion caused; they are essentially the same in terms of the content/code logic and duplicates are due to different forks/pull requests when init. However, I'd suggest pulling from the **WING-NUS** repo as the account is actively managed by the group.

**Comment by GabrielLin** [comment]
OK, thanks for your great work.
